### ISSUE TITLE
i'm using wsl

### ISSUE THREAD

**Issue by PlumpMath** [matthewdowney/excel-clj#2]
hi thanks. 
I try first example. problem below~

(let [;; A workbook is any [key value] seq of [sheet-name, sheet-grid].
      ;; Convert the table to a grid with the table function.
      workbook {"My Generated Sheet" (excel/table table-data)}]
  (excel/quick-open workbook))
**Fontconfig error: Cannot load default config file**

(process:28549): Gtk-WARNING **: 08:45:29.014: Locale not supported by C library.
        Using the fallback 'C' locale.
**Execution error (IOException) at sun.awt.X11.XDesktopPeer/launch (XDesktopPeer.java:124).
Failed to show URI:file:/tmp/generated-sheet16968759586452060480.xlsx**

Thanks! good day~*

**Comment by matthewdowney** [comment]
Hi there, it looks like Java is having trouble working with your OS to open the file. 

- Does it write the file correctly, can you open `/tmp/generated-sheet16968759586452060480.xlsx` manually?
- What OS are you using? 
- [This is a solution] (https://stackoverflow.com/a/11693181) to the same problem you're having for Linux Mint, might be worth a try.

**Comment by PlumpMath** [comment]
(한글을 사용하는건 이해해주세요. 
영어보다 편해서.
그리고 한글로 적는 이유는 여러가지 신념때문입니다.)
(한글로 적는 이유는 이세상 모든 권력문제를 없애기위해,...)
.
NixOS 를 사용합니다.
내가 워낙 nix 골수 팬이라... 
오리지날 NixOS를 사용하다가. 하드디스크가 날아가서.
nix + wsl2 + windows 10 으로 이동했는데.
.
오리지널 your JAR 파일은 LibreOffice for windows 10 에서는 잘되고, 
.
내 문제는 정확히는 wsl2 의 문제는 아니고, 
nix 의 문제입니다.
nix는 모든 소프트웨어를 /nix/store/ 하위에다 설치합니다.
.
어찌됐든. 당신의 링크가 옳습니다.
https://github.com/NixOS/nixpkgs/issues/25556
https://www.reddit.com/r/NixOS/comments/5un4bi/best_way_to_handle_desktop_files_in_user/

둘다 영어로 되어있어서 시도는 제대로 못해봤다 
wsl이라 x를 밖에서 실행해줘야하는 번거로움 때문에.
(한글로 적는 이유는 이세상 모든 권력문제를 없애기위해,... 번거로움을 없애기위해서...)
.
여하튼, 감사합니다. Thanks.

**Comment by matthewdowney** [comment]
Are you able to use the JVM to open files on your version of Linux?

**Comment by PlumpMath** [comment]
<img width="912" alt="캡처" src="https://user-images.githubusercontent.com/1218365/71312738-cbf5a800-2471-11ea-93dc-e398ab74d7c9.PNG">

당연히 되지요.

어쨌든, 내 nix셋팅문제이다. 
어떻게 해결해야될지는 모르겠지만,
당장 필요한것은 아니기 때문에, 
지금 해결해야되는것은 아니지만,
당신이 알려준 해결방법을
나중에 nix에도 적용하는 방법을 천천히 알게되겠지.

**Comment by PlumpMath** [comment]
마지막 원하는 기능 언급한 포인트는...
x의존은 이런것이다.

<img width="367" alt="캡처" src="https://user-images.githubusercontent.com/1218365/71312839-5ee31200-2473-11ea-887d-5b1e4fab311d.PNG">


vcXsrv 를 실행해야만 jar모듈이 초기화 import 됩니다.

<img width="928" alt="캡처" src="https://user-images.githubusercontent.com/1218365/71312841-6a363d80-2473-11ea-8c73-4d22029b2523.PNG">

**Comment by luposlip** [comment]
This issue can probably be mitigated by adding the following environment variable:
```
ENV JAVA_OPTS=-Djava.awt.headless=true
```

In Docker (with JDK8 and newer) it seems to be caused by the depenency to `rhizome` - can you remove that dependency @matthewdowney ?

**Comment by luposlip** [comment]
If you don't want to slim down your library @matthewdowney, I've made a fork here (because I have the same issue):
https://github.com/luposlip/excel-clj

**Comment by matthewdowney** [comment]
You're right, this dependency was not essential & was responsible for headaches. Latest release has it omitted. 

P.S. sorry for the late response — pull requests always welcome!
