### ISSUE TITLE
Periodic issue when generating large Excel files (parallelization?)

### ISSUE THREAD

**Issue by luposlip** [matthewdowney/excel-clj#3]
Hi there!

First of all - I think your approach to generating Excel from Clojure is great and more flexible than the alternatives I've tried.

**When using version 1.2.0:**

There seem to be a periodic issue when generating the exact same files based on the exact same data with the exact same code: Sometimes styles/cells are messed up, and placed incorrectly in the sheet. This means I always have to double check the file, and re-generate it if something looks wrong.

**When using version 1.1.2:**

The issue doesn't seem to be there.

**Conclusion?**

My initial thought is that the cause might be the parallelization feature of 1.2.0, which perhaps doesn't always put the results correctly together?

Best,
Henrik

**Comment by matthewdowney** [comment]
Hey there Henrik,

Thank you for bringing this issue to my attention & for the careful analysis! I'm sorry to hear that this is happening. 

To aid with confirmation of the issue I've just pushed a 1.2.1 version which allows setting a dynamic `*n-threads*` var to control the number of threads used to write the document. 

If you're right and it's an issue with parallelization (it certainly sounds right to me), using only one thread should solve it and provide a quick sledgehammer workaround for the time being. Otherwise I might have relied on something non-deterministic in the version of the sheet writing code that 1.2.0 uses. Either way I'd love to hear back from you to see if the issue is persisting just using one thread, and I'll then investigate an fix accordingly. 

E.g.

```clojure
(require '[excel-clj.core :as excel])

(binding [excel/*n-threads* 1]
  (excel/quick-open 
    {"My Generated Sheet" (excel/table [{"Foo" "Bar"}, {"Foo" "Baz"}])}))
```

Also, thank you, I'm glad to hear it's been useful for you apart from this issue. I'm using some in-development features of this project quite a bit at work right now and am giving serious thought to a v2.0.0. If you have a features that you'd like included just let me know and I'll consider them. 

Best,
Matt

**Comment by luposlip** [comment]
Thanks Matt! I'll test 1.2.1 tomorrow (which where I am means in around 11 hours)! :)

**Comment by matthewdowney** [comment]
Thank you! And great suggestion, that way of handling styling makes a lot more sense than the callback, will certainly include. :)

**Comment by luposlip** [comment]
Looking forward to V2! :)
Actually, the more you can build up only with data, and just call a single `write!` or similar in the end, the better IMO.

Just tested 1.2.1. I wrote my Excel file 3 times without issues.
The 4th time it failed with messed up styles. The 5th time it also put in a few cells incorrectly (styling was fine though). The 6th time everything looked fine again.

Is this enough for you to work with?

**Comment by matthewdowney** [comment]
Definitely, thanks for testing it out. I'll start working on getting to the bottom of the issue and keep you posted. 

> Actually, the more you can build up only with data, and just call a single write! or similar in the end, the better IMO.

That makes a lot of sense to me!

**Comment by matthewdowney** [comment]
Hey Henrik, 

I've made some progress towards a pure-data interface for v2 — I'll open a separate issue for discussion about how the interface should look and how things should work. 

In the meantime, I think I've fixed this bug. I was able to reproduce the styles getting messed up by just writing tables of 10000 rows a few times, even if I was only using one thread to do the writing.

```clojure
(quick-open {"Test" (table
                      (for [x (range 10000)]
                        {"N" x, "N^2" (* x x), "N^3" (* x x x)}))})

```

In the v1.3.0 I've just pushed, I changed the lowest level POI interface to add some more organization around writing cells and removed the old cell writing code, which fixed the issue for me.

I got rid of the multi threading for writing (I think regardless of when the data are actually written, creating cell styles and whatnot is probably not thread safe in POI) and it's now slightly faster at doing the writing in a single thread than the old version was using multiple threads. So it seems like just doing things better was enough to take care of the performance concern as well.

Hopefully this also fixes the issue for you!

**Comment by luposlip** [comment]
Hey Matt!
Sorry for the late reply.
I've tested with 1.3.0, but I get this exception when trying to compile my ns that uses excel-clj:

```
2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling excel_clj/core.clj at (1:1)
   #:clojure.error{:phase :compile-syntax-check,
                   :line 1,
                   :column 1,
                   :source "excel_clj/core.clj"}
                  core.clj: 5867  clojure.core/throw-if
                  core.clj: 5953  clojure.core/load-lib
                  core.clj: 5928  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj: 5985  clojure.core/load-libs
                  core.clj: 5969  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj: 6007  clojure.core/require
                  core.clj: 6007  clojure.core/require
               RestFn.java:  482  clojure.lang.RestFn/invoke
                  core.clj:    1  excel-clj.core/eval13489/loading--auto--
                  core.clj:    1  excel-clj.core/eval13489
                  core.clj:    1  excel-clj.core/eval13489
             Compiler.java: 7177  clojure.lang.Compiler/eval
             Compiler.java: 7166  clojure.lang.Compiler/eval
             Compiler.java: 7636  clojure.lang.Compiler/load
                   RT.java:  381  clojure.lang.RT/loadResourceScript
                   RT.java:  372  clojure.lang.RT/loadResourceScript
                   RT.java:  459  clojure.lang.RT/load
                   RT.java:  424  clojure.lang.RT/load
                  core.clj: 6126  clojure.core/load/fn
                  core.clj: 6125  clojure.core/load
                  core.clj: 6109  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5908  clojure.core/load-one
                  core.clj: 5903  clojure.core/load-one
                  core.clj: 5948  clojure.core/load-lib/fn
                  core.clj: 5947  clojure.core/load-lib
                  core.clj: 5928  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj: 5985  clojure.core/load-libs
                  core.clj: 5969  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj: 6007  clojure.core/require
                  core.clj: 6007  clojure.core/require
               RestFn.java:  482  clojure.lang.RestFn/invoke
             Compiler.java: 7177  clojure.lang.Compiler/eval
             Compiler.java: 7166  clojure.lang.Compiler/eval
             Compiler.java: 7636  clojure.lang.Compiler/load
             Compiler.java: 7177  clojure.lang.Compiler/eval
             Compiler.java: 7132  clojure.lang.Compiler/eval
                  core.clj: 3214  clojure.core/eval
                  core.clj: 3210  clojure.core/eval
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  437  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  665  clojure.core/apply
                  core.clj:  660  clojure.core/apply
                regrow.clj:   18  refactor-nrepl.ns.slam.hound.regrow/wrap-clojure-repl/fn
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   79  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  142  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  171  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  170  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  835  java.lang.Thread/run

1. Caused by java.lang.Exception
   **namespace 'excel-clj.style' not found**
```

Any idea why this happens?

**Comment by matthewdowney** [comment]
I'm very embarrassed to say that I was too eager to `lein deploy` as soon as I got it working with tests passing in my IDE, and didn't  do a `lein check` — I left some `require`s (in excel-clj.style) that were not valid. :man_facepalming:

I deployed a 1.3.1 and double checked by creating a new lein project, requiring it, and generating a document from the REPL. It should be working now!

**Comment by luposlip** [comment]
Probably a new issue (?), but now I get this error (I'm generating an Excel file with multiple sheets, perhaps that causes the issue):

```
1. Unhandled java.lang.IllegalStateException
   Cannot add merged region B10:C10 to sheet because it overlaps with
   an existing merged region (A10:B10).

            XSSFSheet.java:  482  org.apache.poi.xssf.usermodel.XSSFSheet/validateMergedRegions
            XSSFSheet.java:  414  org.apache.poi.xssf.usermodel.XSSFSheet/addMergedRegion
            XSSFSheet.java:  368  org.apache.poi.xssf.usermodel.XSSFSheet/addMergedRegion
                   poi.clj:  128  excel-clj.poi.SheetWriter/write_BANG_
             prototype.clj:  114  excel-clj.prototype/write-rows!/fn
           ArrayChunk.java:   63  clojure.lang.ArrayChunk/reduce
             protocols.clj:  136  clojure.core.protocols/fn
             protocols.clj:  124  clojure.core.protocols/fn
             protocols.clj:   19  clojure.core.protocols/fn/G
             protocols.clj:   31  clojure.core.protocols/seq-reduce
             protocols.clj:   75  clojure.core.protocols/fn
             protocols.clj:   75  clojure.core.protocols/fn
             protocols.clj:   13  clojure.core.protocols/fn/G
                  core.clj: 6828  clojure.core/reduce
                  core.clj: 6810  clojure.core/reduce
             prototype.clj:  110  excel-clj.prototype/write-rows!
             prototype.clj:  106  excel-clj.prototype/write-rows!
             prototype.clj:  132  excel-clj.prototype/write!/fn
             prototype.clj:  129  excel-clj.prototype/write!
             prototype.clj:  121  excel-clj.prototype/write!
                  core.clj:  175  excel-clj.core/write!
                  core.clj:  159  excel-clj.core/write!
```

**Comment by matthewdowney** [comment]
I was able to reproduce this issue by sticking two cells with width > 1 next to each other in the same row:
```clojure
(require '[excel-clj.core :as excel])
(excel/quick-open {"Test" [(repeat 2 {:value "Wide Cell" :width 2})]})
```
  
In v1.1.2 that snippet works, and in v1.3.1 it produces the same error that you're seeing. 

I'm going to:
- add that situation as a test case,
- update the `writer` that 1.3.1 is using under the hood to skip the cursor ahead after writing a wide cell, and
- push a v1.3.2.

Out of curiosity, what sort of formatting are you doing? Are you sticking two tables next to each other horizontally, or making custom titles?

**Comment by luposlip** [comment]
Yeah, I'm doing some custom layout, where I group 2 columns under 1 header several times.
And the first couple of rows also spans multiple cells.

Thanks for your good will - it all seems to work perfectly now :-)
I've generated and manually looked through 11 Excel files, and they look fine! :+1: 

Don't hesitate to ask for more details about how I'm generating the files.
