### ISSUE TITLE
Column width does not adjust for columns after J column

### ISSUE THREAD

**Issue by orolle** [matthewdowney/excel-clj#4]
![grafik](https://user-images.githubusercontent.com/1541570/85586900-9b214600-b641-11ea-9b06-98006ea3c339.png)

I did look at the source code, but I did not find any obvious bug.

**Comment by matthewdowney** [comment]
Should be fixed in the latest release, thank you for reporting!

**Comment by orolle** [comment]
Thanks a lot. The issue is fixed in the snapshot 👍
