### ISSUE TITLE
symbol inst-ms (excel_clj/poi.clj:321:22) cannot be resolved

### ISSUE THREAD

**Issue by toreohm** [matthewdowney/excel-clj#8]
Hello there,
I'm trying to use your library but I get this error:
#error {
 :cause Unable to resolve symbol: inst-ms in this context
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message java.lang.RuntimeException: Unable to resolve symbol: inst-ms in this context, compiling:(excel_clj/poi.clj:321:22)
   :at [clojure.lang.Compiler analyze Compiler.java 6688]}
  {:type java.lang.RuntimeException
   :message Unable to resolve symbol: inst-ms in this context
   :at [clojure.lang.Util runtimeException Util.java 221]}]

Can you fix it please?

**Comment by matthewdowney** [comment]
Hi there, [it looks like](https://clojuredocs.org/clojure.core/inst-ms) `inst-ms` was added in Clojure 1.9. At a minimum, I'll update the README to reflect that being the minimum compatible version of Clojure.

What version of Clojure are you using, and if it's < 1.9, are you able to upgrade?

**Comment by toreohm** [comment]
I'm using clojure 1.8.
I understand now. Thank you
